// <auto-generated />
using System;
using AgendamentoTransporte.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgendamentoTransporte.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250521134638_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("AgendamentoTransporte.Models.Agendamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalBusca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalBuscaOutro")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalConsulta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalConsultaOutro")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoViagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomePaciente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("PontoReferencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrecisaAcompanhante")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioResponsavel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agendamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
